### GET request to example server

POST http://localhost:8080/api/v1/yahtzee/new-game

###

POST http://localhost:8080/api/v1/yahtzee/roll-all

###

POST http://localhost:8080/api/v1/yahtzee/reroll
Content-Type: application/json

[4]

###

POST http://localhost:8080/api/v1/yahtzee/choose-score

###

POST http://localhost:8080/api/v1/yahtzee/score
Content-Type: application/json

{
    "category": "large-straight"
}